In [4]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

Load your data

In [5]:
import pandas as pd
import matplotlib .pyplot as plt
import seaborn as sns
import requests

Get to know your data

In [6]:
df = pd.read_csv('cps_00001.csv.gz')
df.head()

FileNotFoundError: [Errno 2] No such file or directory: 'cps_00001.csv.gz'

In [ ]:
df = pd.read_csv("cps_00001.csv.gz")
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 144265 entries, 0 to 144264
Data columns (total 16 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   YEAR       144265 non-null  int64
 1   REGION     144265 non-null  int64
 2   STATEFIP   144265 non-null  int64
 3   COUNTY     144265 non-null  int64
 4   METRO      144265 non-null  int64
 5   ASECWT     144265 non-null  float64
 6   AGE        144265 non-null  int64
 7   SEX        144265 non-null  int64
 8   RACE       144265 non-null  int64
 9   OCC        144265 non-null  int64
 10  UHRSWORK1  144265 non-null  int64
 11  EDUC       144265 non-null  int64
 12  SCHLCOLL   144265 non-null  int64
 13  INCWAGE    144265 non-null  int64
 14  OFFTOTVAL  144265 non-null  int64
 15  POVERTY    144265 non-null  int64
dtypes: float64(1), int64(15)
memory usage: 17.6 MB

In [ ]:
df = pd.read_csv("cps_00001.csv.gz")
df.shape

(144265, 16)

Explore individual columns

In [ ]:
df = pd.read_csv('cps_00001.csv.gz')
df.columns

Index(['YEAR', 'REGION', 'STATEFIP', 'COUNTY', 'METRO', 'ASECWT', 'AGE', 'SEX',
       'RACE', 'OCC', 'UHRSWORK1', 'EDUC', 'SCHLCOLL', 'INCWAGE', 'OFFTOTVAL',
       'POVERTY'],
      dtype='str')

In [ ]:
df = pd.read_csv('cps_00001.csv.gz')
df.value_counts()

YEAR  REGION  STATEFIP  COUNTY  METRO  ASECWT   AGE  SEX  RACE  OCC   UHRSWORK1  EDUC  SCHLCOLL  INCWAGE   OFFTOTVAL  POVERTY
2024  12      36        36081   2      3678.69  51   2    651   0     999        60    5         0         241319     23         5
      11      25        25025   2      4304.34  54   1    100   4220  40         73    5         50000     714795     23         3
      22      38        0       4      232.98   8    1    100   0     999        1     0         99999999  125000     23         3
              31        0       1      566.46   8    1    100   0     999        1     0         99999999  98000      23         3
              20        0       1      1329.83  11   2    200   0     999        1     0         99999999  150529     23         3
                                                                                                                                ..
      42      15        15003   3      715.41   46   1    100   4810  40         92    5         80000     130826     23         1
                                                45   2    813   4530  40         111   5         50000     130826     23         1
                                       600.53   14   2    813   0     999        1     0         99999999  130826     23         1
                                       489.61   10   2    813   0     999        1     0         99999999  130826     23         1
                                       581.97   9    2    813   0     999        1     0         99999999  130826     23         1
Name: count, Length: 143745, dtype: int64

In [ ]:
df = pd.read_csv('cps_00001.csv.gz')
df.describe()

,YEAR,REGION,STATEFIP,COUNTY,METRO,ASECWT,AGE,SEX,RACE,OCC,UHRSWORK1,EDUC,SCHLCOLL,INCWAGE,OFFTOTVAL,POVERTY
count,144265.0,144265.000000,144265.000000,144265.000000,144265.000000,144265.000000,144265.000000,144265.000000,144265.000000,144265.000000,144265.000000,144265.000000,144265.000000,1.442650e+05,1.442650e+05,144265.000000
mean,2024.0,29.635761,27.860271,9301.235469,2.540117,2303.971754,38.965626,1.511725,177.578512,1991.113298,566.887790,69.266648,2.244578,1.973886e+07,1.766210e+07,21.421246
std,0.0,10.267561,16.398180,14459.075475,0.988342,1409.804171,23.291965,0.499864,184.309410,2769.315801,478.009648,40.829885,2.407057,3.976183e+07,4.184029e+08,4.138372
min,2024.0,11.000000,1.000000,0.000000,0.000000,99.430000,0.000000,1.000000,100.000000,0.000000,0.000000,1.000000,0.000000,0.000000e+00,-2.004300e+04,0.000000
25%,2024.0,21.000000,12.000000,0.000000,2.000000,1211.790000,18.000000,1.000000,100.000000,0.000000,40.000000,40.000000,0.000000,0.000000e+00,4.559600e+04,23.000000
50%,2024.0,31.000000,28.000000,0.000000,3.000000,2199.170000,38.000000,2.000000,100.000000,0.000000,999.000000,73.000000,0.000000,3.800000e+04,9.030000e+04,23.000000
75%,2024.0,41.000000,42.000000,12105.000000,3.000000,3076.020000,58.000000,2.000000,100.000000,4020.000000,999.000000,111.000000,5.000000,1.300000e+05,1.600000e+05,23.000000
max,2024.0,42.000000,56.000000,55139.000000,4.000000,21488.610000,85.000000,2.000000,830.000000,9840.000000,999.000000,125.000000,5.000000,1.000000e+08,1.000000e+10,23.000000

Practice basic cleaning and wrangling

Filter rows using .loc[], .iloc[] and/or boolean indexing

In [ ]:
df[['EDUC','SCHLCOLL','INCWAGE','AGE','SEX','RACE','OCC']].head()
ubi_subset = df[['EDUC','SCHLCOLL','INCWAGE','AGE','SEX','RACE','OCC']]
ubi_subset.info()

<class 'pandas.DataFrame'>
RangeIndex: 144265 entries, 0 to 144264
Data columns (total 7 columns):
 #   Column    Non-Null Count   Dtype
---  ------    --------------   -----
 0   EDUC      144265 non-null  int64
 1   SCHLCOLL  144265 non-null  int64
 2   INCWAGE   144265 non-null  int64
 3   AGE       144265 non-null  int64
 4   SEX       144265 non-null  int64
 5   RACE      144265 non-null  int64
 6   OCC       144265 non-null  int64
dtypes: int64(7)
memory usage: 7.7 MB

In [ ]:
df[['EDUC','SCHLCOLL','INCWAGE','AGE','SEX','RACE','OCC']].head()
ubi_subset = df[['EDUC','SCHLCOLL','INCWAGE','AGE','SEX','RACE','OCC']]
ubi_subset.head()

   EDUC  SCHLCOLL  INCWAGE  AGE  SEX  RACE   OCC
0    73         0        0   85    2   100     0
1    73         0        0   85    1   100     0
2    30         0        0   15    2   100     0
3    73         5        0   53    2   100     0
4    81         5    40000   52    1   100  5240

In [ ]:
df = pd.read_csv('cps_00001.csv.gz')
df = df[['EDUC','SCHLCOLL','INCWAGE','AGE','SEX','RACE','OCC']]
df.loc[0:10,['EDUC','SCHLCOLL','INCWAGE','AGE','SEX','RACE','OCC']]

    EDUC  SCHLCOLL   INCWAGE  AGE  SEX  RACE   OCC
0     73         0         0   85    2   100     0
1     73         0         0   85    1   100     0
2     30         0         0   15    2   100     0
3     73         5         0   53    2   100     0
4     81         5     40000   52    1   100  5240
5     30         0         0   68    1   100     0
6      1         0  99999999   14    2   100     0
7     73         0         0   73    1   100     0
8     73         0         0   72    1   100     0
9     73         0         0   62    2   100     0
10    73         0     61729   63    1   100  6130

In [ ]:
ubi_subset.columns

Index(['EDUC', 'SCHLCOLL', 'INCWAGE', 'AGE', 'SEX', 'RACE', 'OCC'], dtype='str')

In [ ]:
df = pd.read_csv('cps_00001.csv.gz')
df.columns

Index(['YEAR', 'REGION', 'STATEFIP', 'COUNTY', 'METRO', 'ASECWT', 'AGE', 'SEX',
       'RACE', 'OCC', 'UHRSWORK1', 'EDUC', 'SCHLCOLL', 'INCWAGE', 'OFFTOTVAL',
       'POVERTY'],
      dtype='str')

In [ ]:
df = pd.read_csv('cps_00001.csv.gz')
df = df[['YEAR', 'REGION', 'STATEFIP', 'COUNTY', 'METRO', 'ASECWT', 'AGE', 'SEX',
       'RACE', 'OCC', 'UHRSWORK1', 'EDUC', 'SCHLCOLL', 'INCWAGE', 'OFFTOTVAL',
       'POVERTY']]
df.loc[0:10, ['YEAR', 'REGION', 'STATEFIP', 'COUNTY', 'METRO', 'ASECWT', 'AGE', 'SEX',
       'RACE', 'OCC', 'UHRSWORK1', 'EDUC', 'SCHLCOLL', 'INCWAGE', 'OFFTOTVAL',
       'POVERTY']]

,YEAR,REGION,STATEFIP,COUNTY,METRO,ASECWT,AGE,SEX,RACE,OCC,UHRSWORK1,EDUC,SCHLCOLL,INCWAGE,OFFTOTVAL,POVERTY
0,2024,11,23,0,1,601.57,85,2,100,0,999,73,0,0,32206,23
1,2024,11,23,0,1,601.57,85,1,100,0,999,73,0,0,32206,23
2,2024,11,23,0,1,1312.04,15,2,100,0,999,30,0,0,0,10
3,2024,11,23,0,1,1559.99,53,2,100,0,999,73,5,0,50838,23
4,2024,11,23,0,1,1559.99,52,1,100,5240,40,81,5,40000,50838,23
5,2024,11,23,0,1,580.60,68,1,100,0,999,30,0,0,9648,10
6,2024,11,23,0,1,1351.94,14,2,100,0,999,1,0,99999999,9648,10
7,2024,11,23,0,1,1494.38,73,1,100,0,999,73,0,0,16563,21
8,2024,11,23,0,1,1521.46,72,1,100,0,999,73,0,0,35987,23
9,2024,11,23,0,1,1500.23,62,2,100,0,999,73,0,0,71435,23
10,2024,11,23,0,1,1500.23,63,1,100,6130,40,73,0,61729,71435,23

In [ ]:
df = pd.read_csv('cps_00001.csv.gz')
df = df[['YEAR', 'REGION', 'STATEFIP', 'COUNTY', 'METRO', 'ASECWT', 'AGE', 'SEX',
       'RACE', 'OCC', 'UHRSWORK1', 'EDUC', 'SCHLCOLL', 'INCWAGE', 'OFFTOTVAL',
       'POVERTY']]
df.iloc[0:10, 0:17]

,YEAR,REGION,STATEFIP,COUNTY,METRO,ASECWT,AGE,SEX,RACE,OCC,UHRSWORK1,EDUC,SCHLCOLL,INCWAGE,OFFTOTVAL,POVERTY
0,2024,11,23,0,1,601.57,85,2,100,0,999,73,0,0,32206,23
1,2024,11,23,0,1,601.57,85,1,100,0,999,73,0,0,32206,23
2,2024,11,23,0,1,1312.04,15,2,100,0,999,30,0,0,0,10
3,2024,11,23,0,1,1559.99,53,2,100,0,999,73,5,0,50838,23
4,2024,11,23,0,1,1559.99,52,1,100,5240,40,81,5,40000,50838,23
5,2024,11,23,0,1,580.60,68,1,100,0,999,30,0,0,9648,10
6,2024,11,23,0,1,1351.94,14,2,100,0,999,1,0,99999999,9648,10
7,2024,11,23,0,1,1494.38,73,1,100,0,999,73,0,0,16563,21
8,2024,11,23,0,1,1521.46,72,1,100,0,999,73,0,0,35987,23
9,2024,11,23,0,1,1500.23,62,2,100,0,999,73,0,0,71435,23

In [ ]:
df = pd.read_csv('cps_00001.csv.gz')
df = df[['YEAR', 'REGION', 'STATEFIP', 'COUNTY', 'METRO', 'ASECWT', 'AGE', 'SEX',
       'RACE', 'OCC', 'UHRSWORK1', 'EDUC', 'SCHLCOLL', 'INCWAGE', 'OFFTOTVAL',
       'POVERTY']]
df.sort_values(by=['INCWAGE','SEX'])

,YEAR,REGION,STATEFIP,COUNTY,METRO,ASECWT,AGE,SEX,RACE,OCC,UHRSWORK1,EDUC,SCHLCOLL,INCWAGE,OFFTOTVAL,POVERTY
356,2024,11,23,23019,4,1850.71,8,1,100,0,999,1,0,99999999,9999999999,0
752,2024,11,23,23005,4,1135.54,2,1,100,0,999,1,0,99999999,9999999999,0
1404,2024,11,33,0,1,807.28,9,1,100,0,999,1,0,99999999,9999999999,0
1413,2024,11,33,0,1,604.81,12,1,100,0,999,1,0,99999999,9999999999,0
3767,2024,11,50,0,4,330.45,4,1,100,0,999,1,0,99999999,9999999999,0
5159,2024,11,25,25017,3,1523.74,13,1,100,0,999,1,0,99999999,9999999999,0
5793,2024,11,25,25023,3,1795.98,12,1,100,0,999,1,0,99999999,9999999999,0
10606,2024,12,36,0,4,2373.23,13,1,100,0,999,1,0,99999999,9999999999,0
10753,2024,12,36,0,2,3837.15,14,1,200,0,999,1,0,99999999,9999999999,0
12293,2024,12,36,36059,3,2497.56,12,1,300,0,999,1,0,99999999,9999999999,0
12294,2024,12,36,36059,3,2851.96,2,1,300,0,999,1,0,99999999,9999999999,0
19868,2024,12,42,42091,3,6073.15,0,1,100,0,999,1,0,99999999,9999999999,0
22250,2024,21,39,0,1,2950.36,13,1,100,0,999,1,0,99999999,9999999999,0
22480,2024,21,39,0,1,2074.34,14,1,100,0,999,1,0,99999999,9999999999,0
23113,2024,21,39,0,2,2172.23,11,1,100,0,999,1,0,99999999,9999999999,0
23114,2024,21,39,0,2,2172.23,10,1,100,0,999,1,0,99999999,9999999999,0
25856,2024,21,18,18105,4,2219.10,6,1,100,0,999,1,0,99999999,9999999999,0
26082,2024,21,18,18089,4,3154.63,4,1,100,0,999,1,0,99999999,9999999999,0
26271,2024,21,18,0,2,2171.11,7,1,100,0,999,1,0,99999999,9999999999,0
26272,2024,21,18,0,2,3189.97,5,1,100,0,999,1,0,99999999,9999999999,0
26273,2024,21,18,0,2,3427.71,0,1,100,0,999,1,0,99999999,9999999999,0
26451,2024,21,18,0,2,1369.00,14,1,801,0,999,1,0,99999999,9999999999,0
27359,2024,21,18,18141,3,1706.71,1,1,100,0,999,1,0,99999999,9999999999,0
28457,2024,21,17,0,3,2939.55,0,1,100,0,999,1,0,99999999,9999999999,0
33742,2024,21,26,26081,3,2087.25,8,1,100,0,999,1,0,99999999,9999999999,0
35696,2024,21,55,0,2,2173.76,8,1,100,0,999,1,0,99999999,9999999999,0
36544,2024,21,55,55073,4,1720.86,3,1,100,0,999,1,0,99999999,9999999999,0
38152,2024,22,27,0,3,2893.52,11,1,300,0,999,1,0,99999999,9999999999,0
38154,2024,22,27,0,3,3970.08,5,1,300,0,999,1,0,99999999,9999999999,0
38311,2024,22,27,27171,3,3313.85,4,1,100,0,999,1,0,99999999,9999999999,0

Drop or rename columns

In [ ]:
df = pd.read_csv('cps_00001.csv.gz')
df = df[['YEAR', 'REGION', 'STATEFIP', 'COUNTY', 'METRO', 'ASECWT', 'AGE', 'SEX',
       'RACE', 'OCC', 'UHRSWORK1', 'EDUC', 'SCHLCOLL', 'INCWAGE', 'OFFTOTVAL',
       'POVERTY']]
df.drop(['REGION'], axis = 1)

,YEAR,STATEFIP,COUNTY,METRO,ASECWT,AGE,SEX,RACE,OCC,UHRSWORK1,EDUC,SCHLCOLL,INCWAGE,OFFTOTVAL,POVERTY
0,2024,23,0,1,601.57,85,2,100,0,999,73,0,0,32206,23
1,2024,23,0,1,601.57,85,1,100,0,999,73,0,0,32206,23
2,2024,23,0,1,1312.04,15,2,100,0,999,30,0,0,0,10
3,2024,23,0,1,1559.99,53,2,100,0,999,73,5,0,50838,23
4,2024,23,0,1,1559.99,52,1,100,5240,40,81,5,40000,50838,23
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
144260,2024,15,15003,3,715.41,46,1,100,4810,40,92,5,80000,130826,23
144261,2024,15,15003,3,715.41,45,2,813,4530,40,111,5,50000,130826,23
144262,2024,15,15003,3,600.53,14,2,813,0,999,1,0,99999999,130826,23
144263,2024,15,15003,3,489.61,10,2,813,0,999,1,0,99999999,130826,23
144264,2024,15,15003,3,581.97,9,2,813,0,999,1,0,99999999,130826,23

In [ ]:
df = pd.read_csv('cps_00001.csv.gz')
df = df[['YEAR', 'REGION', 'STATEFIP', 'COUNTY', 'METRO', 'ASECWT', 'AGE', 'SEX',
       'RACE', 'OCC', 'UHRSWORK1', 'EDUC', 'SCHLCOLL', 'INCWAGE', 'OFFTOTVAL',
       'POVERTY']]
df.drop(columns=['REGION'],inplace=True)
df.head(5)

,YEAR,STATEFIP,COUNTY,METRO,ASECWT,AGE,SEX,RACE,OCC,UHRSWORK1,EDUC,SCHLCOLL,INCWAGE,OFFTOTVAL,POVERTY
0,2024,23,0,1,601.57,85,2,100,0,999,73,0,0,32206,23
1,2024,23,0,1,601.57,85,1,100,0,999,73,0,0,32206,23
2,2024,23,0,1,1312.04,15,2,100,0,999,30,0,0,0,10
3,2024,23,0,1,1559.99,53,2,100,0,999,73,5,0,50838,23
4,2024,23,0,1,1559.99,52,1,100,5240,40,81,5,40000,50838,23

In [ ]:
df = pd.read_csv('cps_00001.csv.gz')
df = df[['YEAR', 'REGION', 'STATEFIP', 'COUNTY', 'METRO', 'ASECWT', 'AGE', 'SEX',
       'RACE', 'OCC', 'UHRSWORK1', 'EDUC', 'SCHLCOLL', 'INCWAGE', 'OFFTOTVAL',
       'POVERTY']]
df.rename(columns={'STATEFIP': 'STATE/FIP'})

,YEAR,REGION,STATE/FIP,COUNTY,METRO,ASECWT,AGE,SEX,RACE,OCC,UHRSWORK1,EDUC,SCHLCOLL,INCWAGE,OFFTOTVAL,POVERTY
0,2024,11,23,0,1,601.57,85,2,100,0,999,73,0,0,32206,23
1,2024,11,23,0,1,601.57,85,1,100,0,999,73,0,0,32206,23
2,2024,11,23,0,1,1312.04,15,2,100,0,999,30,0,0,0,10
3,2024,11,23,0,1,1559.99,53,2,100,0,999,73,5,0,50838,23
4,2024,11,23,0,1,1559.99,52,1,100,5240,40,81,5,40000,50838,23
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
144260,2024,42,15,15003,3,715.41,46,1,100,4810,40,92,5,80000,130826,23
144261,2024,42,15,15003,3,715.41,45,2,813,4530,40,111,5,50000,130826,23
144262,2024,42,15,15003,3,600.53,14,2,813,0,999,1,0,99999999,130826,23
144263,2024,42,15,15003,3,489.61,10,2,813,0,999,1,0,99999999,130826,23
144264,2024,42,15,15003,3,581.97,9,2,813,0,999,1,0,99999999,130826,23

Check and fix data types if necessary

In [ ]:
df = pd.read_csv('cps_00001.csv.gz')
df = df[['YEAR', 'REGION', 'STATEFIP', 'COUNTY', 'METRO', 'ASECWT', 'AGE', 'SEX',
       'RACE', 'OCC', 'UHRSWORK1', 'EDUC', 'SCHLCOLL', 'INCWAGE', 'OFFTOTVAL',
       'POVERTY']]
df.dtypes

YEAR           int64
REGION         int64
STATEFIP       int64
COUNTY         int64
METRO          int64
ASECWT       float64
AGE            int64
SEX            int64
RACE           int64
OCC            int64
UHRSWORK1      int64
EDUC           int64
SCHLCOLL       int64
INCWAGE        int64
OFFTOTVAL      int64
POVERTY        int64
dtype: object

Use .isna() / .isnull() to identify missing values

In [ ]:
df = pd.read_csv('cps_00001.csv.gz')
df = df[['YEAR', 'REGION', 'STATEFIP', 'COUNTY', 'METRO', 'ASECWT', 'AGE', 'SEX',
       'RACE', 'OCC', 'UHRSWORK1', 'EDUC', 'SCHLCOLL', 'INCWAGE', 'OFFTOTVAL',
       'POVERTY']]
df.isna()

,YEAR,REGION,STATEFIP,COUNTY,METRO,ASECWT,AGE,SEX,RACE,OCC,UHRSWORK1,EDUC,SCHLCOLL,INCWAGE,OFFTOTVAL,POVERTY
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
144260,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
144261,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
144262,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
144263,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
144264,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [ ]:
df = pd.read_csv('cps_00001.csv.gz')
df = df[['YEAR', 'REGION', 'STATEFIP', 'COUNTY', 'METRO', 'ASECWT', 'AGE', 'SEX',
       'RACE', 'OCC', 'UHRSWORK1', 'EDUC', 'SCHLCOLL', 'INCWAGE', 'OFFTOTVAL',
       'POVERTY']]
df.isnull

<bound method DataFrame.isnull of         YEAR  REGION  STATEFIP  COUNTY  METRO   ASECWT  AGE  SEX  RACE   OCC  \
0       2024      11        23       0      1   601.57   85    2   100     0
1       2024      11        23       0      1   601.57   85    1   100     0
2       2024      11        23       0      1  1312.04   15    2   100     0
3       2024      11        23       0      1  1559.99   53    2   100     0
4       2024      11        23       0      1  1559.99   52    1   100  5240
...      ...     ...       ...     ...    ...      ...  ...  ...   ...   ...
144260  2024      42        15   15003      3   715.41   46    1   100  4810
144261  2024      42        15   15003      3   715.41   45    2   813  4530
144262  2024      42        15   15003      3   600.53   14    2   813     0
144263  2024      42        15   15003      3   489.61   10    2   813     0
144264  2024      42        15   15003      3   581.97    9    2   813     0

        UHRSWORK1  EDUC  SCHLCOLL   INCWAGE  OFFTOTVAL  POVERTY
0             999    73         0         0      32206       23
1             999    73         0         0      32206       23
2             999    30         0         0          0       10
3             999    73         5         0      50838       23
4              40    81         5     40000      50838       23
...           ...   ...       ...       ...        ...      ...
144260         40    92         5     80000     130826       23
144261         40   111         5     50000     130826       23
144262        999     1         0  99999999     130826       23
144263        999     1         0  99999999     130826       23
144264        999     1         0  99999999     130826       23

[144265 rows x 16 columns]>

Use .duplicated() to check for duplicate rows and      .drop_duplicates() if needed
Look for early issues such as inconsistent formats or duplicates

In [ ]:
df = pd.read_csv('cps_00001.csv.gz')
df = df[['YEAR', 'REGION', 'STATEFIP', 'COUNTY', 'METRO', 'ASECWT', 'AGE', 'SEX',
       'RACE', 'OCC', 'UHRSWORK1', 'EDUC', 'SCHLCOLL', 'INCWAGE', 'OFFTOTVAL',
       'POVERTY']]
df.duplicated()

0         False
1         False
2         False
3         False
4         False
          ...
144260    False
144261    False
144262    False
144263    False
144264    False
Length: 144265, dtype: bool

This drops duplicates from main df...

In [ ]:
df = pd.read_csv('cps_00001.csv.gz')
df = df[['YEAR', 'REGION', 'STATEFIP', 'COUNTY', 'METRO', 'ASECWT', 'AGE', 'SEX',
       'RACE', 'OCC', 'UHRSWORK1', 'EDUC', 'SCHLCOLL', 'INCWAGE', 'OFFTOTVAL',
       'POVERTY']]
ubi_subset = df[['EDUC','SCHLCOLL','INCWAGE','AGE','SEX','RACE','OCC']]

df.drop_duplicates()

,YEAR,REGION,STATEFIP,COUNTY,METRO,ASECWT,AGE,SEX,RACE,OCC,UHRSWORK1,EDUC,SCHLCOLL,INCWAGE,OFFTOTVAL,POVERTY
0,2024,11,23,0,1,601.57,85,2,100,0,999,73,0,0,32206,23
1,2024,11,23,0,1,601.57,85,1,100,0,999,73,0,0,32206,23
2,2024,11,23,0,1,1312.04,15,2,100,0,999,30,0,0,0,10
3,2024,11,23,0,1,1559.99,53,2,100,0,999,73,5,0,50838,23
4,2024,11,23,0,1,1559.99,52,1,100,5240,40,81,5,40000,50838,23
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
144260,2024,42,15,15003,3,715.41,46,1,100,4810,40,92,5,80000,130826,23
144261,2024,42,15,15003,3,715.41,45,2,813,4530,40,111,5,50000,130826,23
144262,2024,42,15,15003,3,600.53,14,2,813,0,999,1,0,99999999,130826,23
144263,2024,42,15,15003,3,489.61,10,2,813,0,999,1,0,99999999,130826,23
144264,2024,42,15,15003,3,581.97,9,2,813,0,999,1,0,99999999,130826,23

This drops duplicates from the subset...

In [ ]:
df = pd.read_csv('cps_00001.csv.gz')
df = df[['YEAR', 'REGION', 'STATEFIP', 'COUNTY', 'METRO', 'ASECWT', 'AGE', 'SEX',
       'RACE', 'OCC', 'UHRSWORK1', 'EDUC', 'SCHLCOLL', 'INCWAGE', 'OFFTOTVAL',
       'POVERTY']]
ubi_subset = df[['EDUC','SCHLCOLL','INCWAGE','AGE','SEX','RACE','OCC']]
ubi_subset = ubi_subset.drop_duplicates()
df.head(15)

,YEAR,REGION,STATEFIP,COUNTY,METRO,ASECWT,AGE,SEX,RACE,OCC,UHRSWORK1,EDUC,SCHLCOLL,INCWAGE,OFFTOTVAL,POVERTY
0,2024,11,23,0,1,601.57,85,2,100,0,999,73,0,0,32206,23
1,2024,11,23,0,1,601.57,85,1,100,0,999,73,0,0,32206,23
2,2024,11,23,0,1,1312.04,15,2,100,0,999,30,0,0,0,10
3,2024,11,23,0,1,1559.99,53,2,100,0,999,73,5,0,50838,23
4,2024,11,23,0,1,1559.99,52,1,100,5240,40,81,5,40000,50838,23
5,2024,11,23,0,1,580.60,68,1,100,0,999,30,0,0,9648,10
6,2024,11,23,0,1,1351.94,14,2,100,0,999,1,0,99999999,9648,10
7,2024,11,23,0,1,1494.38,73,1,100,0,999,73,0,0,16563,21
8,2024,11,23,0,1,1521.46,72,1,100,0,999,73,0,0,35987,23
9,2024,11,23,0,1,1500.23,62,2,100,0,999,73,0,0,71435,23
10,2024,11,23,0,1,1500.23,63,1,100,6130,40,73,0,61729,71435,23
11,2024,11,23,0,1,1720.54,32,2,100,0,999,73,5,0,71435,23
12,2024,11,23,0,1,1351.18,58,1,100,0,999,73,0,0,54000,23
13,2024,11,23,0,1,1351.18,55,2,100,0,999,73,0,0,54000,23
14,2024,11,23,0,1,1351.18,57,1,100,4220,45,73,0,43000,100007,23

.value_counts() for categorical variables

In [ ]:
df = pd.read_csv('cps_00001.csv.gz')
df = df[['YEAR', 'REGION', 'STATEFIP', 'COUNTY', 'METRO', 'ASECWT', 'AGE', 'SEX',
       'RACE', 'OCC', 'UHRSWORK1', 'EDUC', 'SCHLCOLL', 'INCWAGE', 'OFFTOTVAL',
       'POVERTY']]
ubi_subset = df[['EDUC','SCHLCOLL','INCWAGE','AGE','SEX','RACE','OCC']]
ubi_subset = ubi_subset.drop_duplicates()
df['RACE'].value_counts()
#

RACE
100    110537
200     16207
651      9920
300      2216
801      1499
802      1178
803       931
652       828
804       161
809       150
813       150
805       130
810       123
806        68
811        48
807        34
812        21
830        21
808        18
816         6
814         5
818         4
820         4
815         3
817         2
819         1
Name: count, dtype: int64

A mapping dictionary for race/ethnicity code

In [ ]:
df = pd.read_csv('cps_00001.csv.gz')
df = df[['YEAR', 'REGION', 'STATEFIP', 'COUNTY', 'METRO', 'ASECWT', 'AGE', 'SEX',
       'RACE', 'OCC', 'UHRSWORK1', 'EDUC', 'SCHLCOLL', 'INCWAGE', 'OFFTOTVAL',
       'POVERTY']]
ubi_subset = df[['EDUC','SCHLCOLL','INCWAGE','AGE','SEX','RACE','OCC']]
race_map = {
    100: 'White',
    200: 'Black',
    300: 'American Indian',
    651: 'Asian Indian',
    652: 'Chinese',
    801: 'White & Black',
    802: 'White & AIAN',
    803: 'White & Asian',
    804: 'Black & AIAN',
    805: 'Black & Asian',
    806: 'AIAN & Asian'
}
ubi_subset['RACE_LABEL'] = ubi_subset['RACE'].map(race_map)
ubi_subset['RACE_LABEL'].value_counts()

RACE_LABEL
White              110537
Black               16207
Asian Indian         9920
American Indian      2216
White & Black        1499
White & AIAN         1178
White & Asian         931
Chinese               828
Black & AIAN          161
Black & Asian         130
AIAN & Asian           68
Name: count, dtype: int64

Mapping for 'sex codes: male and female'; same for 'sex' codes...

In [ ]:
sex_map = {
    1: 'Male',
    2: 'Female'
}

ubi_subset['SEX_LABEL'] = ubi_subset['SEX'].map(sex_map)
ubi_subset['SEX_LABEL'].value_counts()

SEX_LABEL
Female    73824
Male      70441
Name: count, dtype: int64

Median income by race AND sex

In [ ]:
ubi_subset.groupby(['RACE_LABEL','SEX_LABEL'])['INCWAGE'].median()

RACE_LABEL       SEX_LABEL
AIAN & Asian     Female       99999999.0
                 Male           144000.0
American Indian  Female          27000.0
                 Male            35000.0
Asian Indian     Female          30000.0
                 Male            60000.0
Black            Female          25000.0
                 Male            35000.0
Black & AIAN     Female          40000.0
                 Male            74000.0
Black & Asian    Female          16000.0
                 Male            33460.0
Chinese          Female          24500.0
                 Male            40000.0
White            Female          27000.0
                 Male            50000.0
White & AIAN     Female          23352.5
                 Male            42500.0
White & Asian    Female         107770.0
                 Male           116669.0
White & Black    Female          60000.0
                 Male            80000.0
Name: INCWAGE, dtype: float64

In [ ]:
import numpy as np

ubi_subset['INCWAGE'] = ubi_subset['INCWAGE'].replace(99999999, np.nan)
ubi_subset = ubi_subset.dropna(subset=['INCWAGE'])
ubi_subset = ubi_subset[ubi_subset['INCWAGE'] > 0]
ubi_subset.head(100)

     EDUC  SCHLCOLL   INCWAGE  AGE  SEX  RACE   OCC       RACE_LABEL SEX_LABEL
4      81         5   40000.0   52    1   100  5240            White      Male
10     73         0   61729.0   63    1   100  6130            White      Male
14     73         0   43000.0   57    1   100  4220            White      Male
15     73         0   25000.0   57    2   100  9005            White    Female
16     73         5   20000.0   23    1   100  9620            White      Male
..    ...       ...       ...  ...  ...   ...   ...              ...       ...
251   111         5   33000.0   35    2   100  2300            White    Female
252    81         5   75000.0   34    1   200  4200            Black      Male
254   125         5  105000.0   44    1   100  2205            White      Male
255   123         5   40000.0   37    1   100  2633            White      Male
256    73         0   72000.0   58    1   300  6200  American Indian      Male

[100 rows x 9 columns]

Occupation only

In [ ]:
df = pd.read_csv('cps_00001.csv.gz')
df = df[['YEAR', 'REGION', 'STATEFIP', 'COUNTY', 'METRO', 'ASECWT', 'AGE', 'SEX',
       'RACE', 'OCC', 'UHRSWORK1', 'EDUC', 'SCHLCOLL', 'INCWAGE', 'OFFTOTVAL',
       'POVERTY']]
ubi_subset = df[['EDUC','SCHLCOLL','INCWAGE','AGE','SEX','RACE','OCC']]
ubi_subset = ubi_subset[['OCC']]
ubi_subset['OCC'].unique()
df['OCC'].value_counts()
df = df[df['OCC'] != 0]
df['OCC'].value_counts().head(50)

OCC
440     2495
2310    1630
3255    1557
9130    1543
4700    1323
4720    1213
4760    1185
5240    1178
4220    1098
6260    1093
9620    1053
4020     981
5740     837
4110     822
1021     822
3602     791
9645     759
10       743
800      735
4230     730
2545     671
120      670
3603     623
20       614
6230     613
8990     611
5860     563
5120     560
4710     552
5000     537
2100     529
220      528
5400     525
4251     513
310      498
710      496
1108     492
205      491
230      480
2205     473
4850     459
2360     452
4600     450
4030     449
6355     445
4920     427
6050     421
3090     417
7200     417
7750     415
Name: count, dtype: int64

Converting CPS job codes into their occupation labels

In [ ]:
df = pd.read_csv('cps_00001.csv.gz')

df = df[['OCC']]

dataset_codes = df['OCC'].unique()

In [ ]:
with open('occ_codebook.txt', 'r', encoding='utf-8') as oc:
    lines = oc.read().splitlines()

In [ ]:
occ_dict = {}

current_code = None

for line in lines:
    line = line.strip()

    if line == "":
        continue

    # if it's numeric, treat as code candidate
    if line.isdigit():
        current_code = line.zfill(4)   # normalize EVERYTHING to 4-digit
    else:
        # treat as label
        if current_code is not None:
            occ_dict[current_code] = line
            current_code = None

In [ ]:
df = pd.read_csv('cps_00001.csv.gz')
df = df[['YEAR', 'REGION', 'STATEFIP', 'COUNTY', 'METRO', 'ASECWT', 'AGE', 'SEX',
       'RACE', 'OCC', 'UHRSWORK1', 'EDUC', 'SCHLCOLL', 'INCWAGE', 'OFFTOTVAL',
       'POVERTY']]
ubi_subset = df[['EDUC','SCHLCOLL','INCWAGE','AGE','SEX','RACE','OCC']]
ubi_subset['INCWAGE'] = ubi_subset['INCWAGE'].replace(99999999, np.nan)
ubi_subset = ubi_subset.dropna(subset=['INCWAGE'])
ubi_subset = ubi_subset[ubi_subset['INCWAGE'] > 0]
ubi_subset.head(10)

    EDUC  SCHLCOLL  INCWAGE  AGE  SEX  RACE   OCC
4     81         5  40000.0   52    1   100  5240
10    73         0  61729.0   63    1   100  6130
14    73         0  43000.0   57    1   100  4220
15    73         0  25000.0   57    2   100  9005
16    73         5  20000.0   23    1   100  9620
21    91         0  80000.0   58    1   100  6355
24    81         0  45000.0   61    2   100  3515
28    73         5   5000.0   41    2   802  3601
31   123         5  72000.0   41    2   100  2205
36    73         0  42000.0   57    1   100  4220

In [ ]:
print(len(occ_dict))           # should be ~800–1000 entries
print(occ_dict.get("0010"))    # Chief executives
print(occ_dict.get("5240"))    # Customer service representatives

569
Chief executives
Customer service representatives

In [ ]:
for i in range(15):
    print(repr(lines[i]))

''
'0000'
'Not in universe'
'0010'
'Chief executives'
'0020'
'General and operations managers'
'0030'
'Legislators'
'0040'
'Advertising and promotions managers'
'0050'
'Marketing and sales managers'
'0060'
'Public relations managers'

Mapping method:  replaces each code with its label
unmatched values become NaN

In [11]:
df["OCC_LABEL"] = df["OCC"].map(occ_dict)
df.head(300)

,YEAR,REGION,STATEFIP,COUNTY,METRO,ASECWT,AGE,SEX,RACE,OCC,UHRSWORK1,EDUC,SCHLCOLL,INCWAGE,OFFTOTVAL,POVERTY,OCC_LABEL
0,2024,11,23,0,1,601.57,85,2,100,0000,999,73,0,0,32206,23,Not in universe
1,2024,11,23,0,1,601.57,85,1,100,0000,999,73,0,0,32206,23,Not in universe
2,2024,11,23,0,1,1312.04,15,2,100,0000,999,30,0,0,0,10,Not in universe
3,2024,11,23,0,1,1559.99,53,2,100,0000,999,73,5,0,50838,23,Not in universe
4,2024,11,23,0,1,1559.99,52,1,100,5240,40,81,5,40000,50838,23,Customer service representatives
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
295,2024,11,23,0,1,2474.83,36,1,200,0000,999,111,5,0,40000,23,Not in universe
296,2024,11,23,0,1,1484.70,35,2,651,1021,40,123,5,72000,359339,23,NaN
297,2024,11,23,0,1,1484.70,35,1,100,3090,40,125,5,270000,359339,23,NaN
298,2024,11,23,0,1,764.19,79,1,100,0000,999,73,0,800,46027,22,Not in universe
299,2024,11,23,0,1,764.19,80,2,100,0000,999,81,0,0,46027,22,Not in universe

Merge method-Turn your dictionary into a DataFrame...

In [13]:

df = pd.read_csv("cleaning_keystone_dataset/cps_00001.csv.gz")
df = df[['YEAR', 'REGION', 'STATEFIP', 'COUNTY', 'METRO', 'ASECWT', 'AGE', 'SEX',
       'RACE', 'OCC', 'UHRSWORK1', 'EDUC', 'SCHLCOLL', 'INCWAGE', 'OFFTOTVAL',
       'POVERTY']]

with open("cleaning_keystone_dataset/occ_codebook.txt", "r", encoding="utf-8") as f:
    lines = f.readlines()

occ_dict = {}

current_code = None

for line in lines:
    line = line.strip()

    if line == "":
        continue

    # if it's numeric, treat as code candidate
    if line.isdigit():
        current_code = line.zfill(4)   # normalize EVERYTHING to 4-digit
    else:
        # treat as label
        if current_code is not None:
            occ_dict[current_code] = line

df["OCC"] = df["OCC"].astype(str).str.zfill(4)
df["OCC_LABEL"] = df["OCC"].map(occ_dict)          


ubi_subset = df[['EDUC','SCHLCOLL','INCWAGE','AGE','SEX','RACE','OCC','OCC_LABEL']]

race_map = {
    100: 'White',
    200: 'Black',
    300: 'American Indian',
    651: 'Asian Indian',
    652: 'Chinese',
    801: 'White & Black',
    802: 'White & AIAN',
    803: 'White & Asian',
    804: 'Black & AIAN',
    805: 'Black & Asian',
    806: 'AIAN & Asian'
}
ubi_subset['RACE_LABEL'] = ubi_subset['RACE'].map(race_map)

sex_map = {
    1: 'Male',
    2: 'Female'
}

ubi_subset['SEX_LABEL'] = ubi_subset['SEX'].map(sex_map)

ubi_subset['INCWAGE'] = ubi_subset['INCWAGE'].replace(99999999, np.nan)
ubi_subset = ubi_subset.dropna(subset=['INCWAGE'])
ubi_subset = ubi_subset[ubi_subset['INCWAGE'] > 0]

result = ubi_subset.groupby(
    ['RACE_LABEL', 'SEX_LABEL']
)['INCWAGE'].median().reset_index()

# result = result.sort_values('INCWAGE', ascending=False)
result

         RACE_LABEL SEX_LABEL  INCWAGE
0      AIAN & Asian    Female  25000.0
1      AIAN & Asian      Male  60000.0
2   American Indian    Female  35000.0
3   American Indian      Male  40000.0
4      Asian Indian    Female  54000.0
5      Asian Indian      Male  72000.0
6             Black    Female  40000.0
7             Black      Male  50000.0
8      Black & AIAN    Female  40000.0
9      Black & AIAN      Male  44500.0
10    Black & Asian    Female  42000.0
11    Black & Asian      Male  52002.0
12          Chinese    Female  35500.0
13          Chinese      Male  47000.0
14            White    Female  42000.0
15            White      Male  60000.0
16     White & AIAN    Female  36000.0
17     White & AIAN      Male  44000.0
18    White & Asian    Female  46000.0
19    White & Asian      Male  60000.0
20    White & Black    Female  30000.0
21    White & Black      Male  35000.0